import '../../app/globals.css';
import { Roboto } from 'next/font/google';
import Sidebar from '@/components/auth/sidebar';
import Main from '@/components/auth/main';
import { Metadata } from "next";

const roboto = Roboto({
    subsets: ['latin'],
    weight: ['300', '400', '500', '700'],
});
export const metadata: Metadata = {
    title: 'Acesso ao Sistema',
    description: 'Generated by create next app',
};
export default function RootLayout({ children }: { children: React.ReactNode }) {

    return (
        <html lang="en">
            <body className={`${roboto.className} antialiased`}>
                <main className="bg-gray-100 h-screen bg-">
                    <Sidebar />
                    <Main>{children}</Main>
                </main>
            </body>
        </html>
    );
}
